//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfoSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Dept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dept()
        {
            this.Emps = new HashSet<Emp>();
        }
    
        [DisplayName("部門ID")]
        [Required(ErrorMessage = "{0}は必須です")]
        public int DeptId { get; set; }

        [DisplayName("部門名")]
        [Required(ErrorMessage = "{0}は必須です")]

        public string DeptName { get; set; }

        [DisplayName("住所")]
        [Required(ErrorMessage = "{0}は必須です")]

        public string Address { get; set; }

        [DisplayName("電話番号")]
        [Required(ErrorMessage = "{0}は必須です")]
        //[RegularExpression("[0-9]{3}-[0-9]{4}-[0-9]{4}", ErrorMessage ="{0}は電話番号形式で入力してください")]
        //[Phone(ErrorMessage = "{0}は電話番号形式で入力してください")]
        [RegularExpression(@"\d{10,11}", ErrorMessage = "正しい電話番号ではありません。")]
        public string Tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp> Emps { get; set; }
    }
}
